using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEngine;

namespace InvisibilityPotion.Items
{
    /// <summary>
    /// Status-effect icons embedded as PNG resources (<c>Icons/*.png</c>, generated by
    /// <c>tools/icons/make_status_icons.py</c>). Each sprite is loaded once and cached by name.
    /// Names: se_veil_t1, se_veil_t2, se_veil_t3, se_veil_broken, se_veil_cooldown.
    /// </summary>
    public static class Icons
    {
        private const string ResourcePrefix = "InvisibilityPotion.Icons.";
        private static readonly Dictionary<string, Sprite> _cache = new Dictionary<string, Sprite>();

        /// <summary>The sprite for an embedded icon name (without ".png"), or null and an error log if it cannot be loaded.</summary>
        public static Sprite Sprite(string name)
        {
            if (string.IsNullOrEmpty(name)) return null;
            if (_cache.TryGetValue(name, out var cached)) return cached;
            Sprite sprite = null;
            try
            {
                sprite = Load(name);
            }
            catch (Exception e)
            {
                Plugin.Log.LogError($"Icon '{name}' failed to load: {e}");
            }
            // cache failures too, so a missing icon logs once instead of on every call
            _cache[name] = sprite;
            return sprite;
        }

        /// <summary>The veil icon of a tier (1..3), or null for an invalid tier.</summary>
        public static Sprite Veil(int tier) => tier >= 1 && tier <= 3 ? Sprite($"se_veil_t{tier}") : null;

        private static Sprite Load(string name)
        {
            byte[] bytes;
            using (var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(ResourcePrefix + name + ".png"))
            {
                if (stream == null)
                {
                    Plugin.Log.LogError($"Icon resource '{ResourcePrefix}{name}.png' not found");
                    return null;
                }
                using (var ms = new MemoryStream())
                {
                    stream.CopyTo(ms);
                    bytes = ms.ToArray();
                }
            }
            var tex = new Texture2D(2, 2, TextureFormat.RGBA32, true);  // mipmaps: the HUD draws it well below 128 px
            // Jotunn wrapper: referencing ImageConversion.LoadImage directly fails on net48 (CS1705, the module targets netstandard 2.1)
            if (!Jotunn.Utils.AssetUtils.LoadImage(tex, bytes))
            {
                Plugin.Log.LogError($"Icon '{name}' is not a valid PNG");
                UnityEngine.Object.Destroy(tex);
                return null;
            }
            tex.name = "ip_" + name;
            tex.wrapMode = TextureWrapMode.Clamp;
            tex.filterMode = FilterMode.Bilinear;
            var sprite = UnityEngine.Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height), new Vector2(0.5f, 0.5f), 100f);
            sprite.name = "ip_" + name;
            return sprite;
        }
    }
}
